CREATE TABLE saves (
     id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
     points INTEGER NOT NULL,
     upgradeAmount INTEGER NOT NULL,
     hasWon BOOLEAN NOT NULL
);